backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /back

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /front

app:
    resource: '@AppBundle/Controller/'
    type: annotation
