<?php

namespace BackendBundle\Repository;
use Doctrine\ORM\EntityRepository;
use BackendBundle\Entity\Job;
use Symfony\Component\Security\Acl\Exception\Exception;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    public function getJobs(){
        return $this->getEntityManager()
            ->getRepository('BackendBundle:Job')
            ->createQueryBuilder('j')
            ->select('j')
            ->getQuery()
            ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }

    public function createJob($job)
    {
        $em = $this->getEntityManager();

        try {
            $em->persist($job);
            $em->flush();
            return $job->getName();
        } catch (\Exception $e) {
            return false;
        }
    }


}
